server:
  port : 8761

eureka:
  instance:
    hostname : localhost
    prefer-ip-address: true
    ip-address: 119.45.136.121
  client:
    registerWithEureka : false
    fetchRegistry : false
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
